-- Continuar aunque existan errores (ej: tabla ya existe ORA-00955)
DROP TABLE ALERT CASCADE CONSTRAINTS;
DROP TABLE PATIENTCONTACT CASCADE CONSTRAINTS;
DROP TABLE PATIENTCONDITION CASCADE CONSTRAINTS;
DROP TABLE PATIENTWEARABLE CASCADE CONSTRAINTS;
DROP TABLE PATIENT CASCADE CONSTRAINTS;
DROP TABLE EMERGENCY_CONTACT CASCADE CONSTRAINTS;
DROP TABLE MEDICAL_CONDITION CASCADE CONSTRAINTS;
DROP TABLE WEARABLE CASCADE CONSTRAINTS;
DROP TABLE ALERT_TYPE CASCADE CONSTRAINTS;
DROP TABLE ROOM CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_ESTUDIANTE;

WHENEVER SQLERROR CONTINUE

CREATE TABLE ROOM (
    ROOMID VARCHAR2(50) PRIMARY KEY,
    FLOOR NUMBER,
    ROOMNUMBER VARCHAR2(50),
    ROOMPAVILION VARCHAR2(50)
);

CREATE TABLE ALERT_TYPE (
    ALERTTYPEID VARCHAR2(50) PRIMARY KEY,
    NAME VARCHAR2(50),
    CODE VARCHAR2(20),
    DESCRIPTION CLOB
);

CREATE TABLE WEARABLE (
    WEARABLEID VARCHAR2(50) PRIMARY KEY,
    MACADDRESS VARCHAR2(20),
    BATTERYLEVEL NUMBER,
    ISACTIVE NUMBER(1) DEFAULT 1
);

CREATE TABLE MEDICAL_CONDITION (
    CONDITIONID VARCHAR2(50) PRIMARY KEY,
    NAME VARCHAR2(50),
    DIAGNOSTIC CLOB,
    ALLERGENTYPE VARCHAR2(50),
    ISCONTAGIOUS NUMBER(1),
    TRANSMISSIONROUTE VARCHAR2(60)
);

CREATE TABLE EMERGENCY_CONTACT (
    CONTACTID VARCHAR2(50) PRIMARY KEY,
    FIRSTNAME VARCHAR2(50),
    LASTNAME VARCHAR2(50),
    PHONE VARCHAR2(50),
    MAIL VARCHAR2(50)
);

CREATE TABLE PATIENT (
    PATIENTID VARCHAR2(50) PRIMARY KEY,
    FIRSTNAME VARCHAR2(50) NOT NULL,
    LASTNAME VARCHAR2(50) NOT NULL,
    DATEOFBIRTH TIMESTAMP,
    ROOMID VARCHAR2(50),
    CONSTRAINT FK_PATIENT_ROOM FOREIGN KEY (ROOMID) REFERENCES ROOM(ROOMID) ON DELETE SET NULL
);

CREATE TABLE PATIENTWEARABLE (
    PATIENTID VARCHAR2(50),
    WEARABLEID VARCHAR2(50),
    ASSIGNEDDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PATIENTWEARABLE PRIMARY KEY (PATIENTID, WEARABLEID),
    CONSTRAINT FK_PW_PATIENT FOREIGN KEY (PATIENTID) REFERENCES PATIENT(PATIENTID) ON DELETE CASCADE,
    CONSTRAINT FK_PW_WEARABLE FOREIGN KEY (WEARABLEID) REFERENCES WEARABLE(WEARABLEID) ON DELETE CASCADE
);

CREATE TABLE PATIENTCONDITION (
    PATIENTID VARCHAR2(50),
    CONDITIONID VARCHAR2(50),
    DIAGNOSTIC CLOB,
    CONSTRAINT PK_PATIENTCONDITION PRIMARY KEY (PATIENTID, CONDITIONID),
    CONSTRAINT FK_PC_PATIENT FOREIGN KEY (PATIENTID) REFERENCES PATIENT(PATIENTID) ON DELETE CASCADE,
    CONSTRAINT FK_PC_CONDITION FOREIGN KEY (CONDITIONID) REFERENCES MEDICAL_CONDITION(CONDITIONID) ON DELETE CASCADE
);

CREATE TABLE PATIENTCONTACT (
    PATIENTID VARCHAR2(50),
    CONTACTID VARCHAR2(50),
    RELATIONSHIP VARCHAR2(50),
    CONSTRAINT PK_PATIENTCONTACT PRIMARY KEY (PATIENTID, CONTACTID),
    CONSTRAINT FK_PCONT_PATIENT FOREIGN KEY (PATIENTID) REFERENCES PATIENT(PATIENTID) ON DELETE CASCADE,
    CONSTRAINT FK_PCONT_CONTACT FOREIGN KEY (CONTACTID) REFERENCES EMERGENCY_CONTACT(CONTACTID) ON DELETE CASCADE
);

CREATE TABLE ALERT (
    ALERTID VARCHAR2(50) PRIMARY KEY,
    PATIENTID VARCHAR2(50),
    WEARABLEID VARCHAR2(50),
    ALERTSTATUS VARCHAR2(30),
    ALERTLEVEL VARCHAR2(30),
    ALERTTYPE VARCHAR2(50),
    NURSEID VARCHAR2(50),
    CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    RESOLVEDAT TIMESTAMP,
    CONSTRAINT FK_ALERT_PATIENT FOREIGN KEY (PATIENTID) REFERENCES PATIENT(PATIENTID) ON DELETE CASCADE,
    CONSTRAINT FK_ALERT_WEARABLE FOREIGN KEY (WEARABLEID) REFERENCES WEARABLE(WEARABLEID) ON DELETE SET NULL,
    CONSTRAINT FK_ALERT_TYPE FOREIGN KEY (ALERTTYPE) REFERENCES ALERT_TYPE(ALERTTYPEID) ON DELETE SET NULL
);

-- ==========================================
-- ESTRUCTURA PREVIA (ESTUDIANTE)
-- ==========================================
CREATE SEQUENCE SEQ_ESTUDIANTE START WITH 1 INCREMENT BY 1;
CREATE TABLE ESTUDIANTE (
    ID NUMBER DEFAULT SEQ_ESTUDIANTE.NEXTVAL PRIMARY KEY,
    CODIGO VARCHAR2(50),
    NOMBRE VARCHAR2(100),
    CARRERA_ID NUMBER
);
